from openai import OpenAI

# Initialize OpenAI client and define model
OPENAI_CLIENT = OpenAI()
GPT_MODEL = "gpt-4o"

def get_response(messages):
    """
    Generates a response from OpenAI GPT-4o model based on given messages.

    Args:
        messages (list): List of dictionaries containing messages with roles and content.

    Returns:
        str: Response generated by the GPT-4o model.
    """
    completion = OPENAI_CLIENT.chat.completions.create(
        model=GPT_MODEL,
        messages=messages
    )
    return completion.choices[0].message.content

def main():
    #initalize messages
    messages=[ 
        {"role": "system", "content": "You are a helpfull assistant."}
        ]
    #prompt - answer loop
    while True:
        user_input = input("Enter your prompt (or 'quit' to exit): ")
        if user_input.lower() == 'quit':
            break
        messages.append({"role": "user", "content": user_input})
        response = get_response(messages)
        print(response)
        messages.append({"role": "assistant", "content": response})

if __name__ == "__main__":
    main()